Repository ramp4-pcar4/storylines-editor, pull requests merged in 2025-07, with the labels that each got.

#633 Made storyline text layout match text preview layout
  package-lock.json
  package.json
  src/style.css
  tailwind.config.js
Labels: PR: Frontend

#679 Slackbot: Improve link handling (block all exterior links)
  .github/slack-bot.py
Labels: PR: Build

#666 refactor: Standardize more common CSS elements
  src/components/editor.vue
  src/components/home.vue
  src/components/metadata/metadata-editor.vue
  src/components/slide-editor.vue
  src/components/slide-toc/slide-toc.vue
  src/components/support/colour-picker-input.vue
  src/standard-components.css
Labels: Refactor, UI/UX, PR: Frontend

#678 Update preview language button
  src/components/preview.vue
Labels: PR: Frontend

#673 added iframe title
  src/components/support/video-preview.vue
Labels: PR: Frontend

#684 Remove inner time slider labels
  src/style.css
Labels: PR: Frontend

#685 Sanitize text panel content upon saving
  package-lock.json
  package.json
  src/components/panel-editors/text-editor.vue
  src/components/slide-editor.vue
Labels: PR: Active, PR: Frontend

#595 Enhance admin upload
  package-lock.json
  package.json
  server/index.js
  src/components/home.vue
  src/components/panel-editors/image-editor.vue
  src/lang/lang.csv
Labels: PR: Active
