Repository ramp4-pcar4/storylines-editor, pull requests merged in 2025-03, with the labels that each got.

#530 Redesign header area
  index-ca-en.html
  index-ca-fr.html
  src/components/editor.vue
  src/components/home.vue
  src/components/metadata-editor.vue
  src/components/slide-editor.vue
  src/lang/lang.csv
Labels: PR: Active, PR: Frontend

#558 Fix behavior of UUID input on Enter press
  src/components/metadata-editor.vue
Labels: PR: Frontend

#553 Delay metadata component load until after config is received
  src/components/metadata-editor.vue
Labels: PR: Frontend

#556 Prevent addition of illegal characters to new/renamed UUIDs
  src/components/metadata-editor.vue
  src/lang/lang.csv
Labels: PR: Frontend

#565 Add a spinner when loading product from dashboard
  src/components/home.vue
  src/components/metadata-editor.vue
Labels: PR: Frontend

#555 Load product on page lang change and router param update
  server/index.js
  src/components/metadata-editor.vue
  src/router/index.ts
Labels: PR: Active

#562 Add panel type mini-icons
  src/assets/audio-editor.svg
  src/assets/chart-editor.svg
  src/assets/dynamic-editor.svg
  src/assets/image-editor.svg
  src/assets/map-editor.svg
  src/assets/slideshow-editor.svg
  src/assets/text-editor.svg
  src/assets/video-editor.svg
  src/components/helpers/slide-toc-button.vue
  src/components/slide-editor.vue
  src/components/slide-toc.vue
  src/definitions.ts
  src/lang/lang.csv
Labels: PR: Frontend

#531 Close BroadcastChannel upon lang change in preview
  src/components/editor.vue
  src/components/preview.vue
  src/stores/lockStore.ts
Labels: PR: Build, PR: Frontend
