Repository ramp4-pcar4/storylines-editor, pull requests merged in 2025-04, with the labels that each got.

#532 Remove redundant schema file, Remove editor-exclusive props from schema
  StorylinesSchema.json
  package-lock.json
  package.json
  public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
  public/StorylinesSlideSchema.json
  server/index.js
  src/components/chart-editor.vue
  src/components/dynamic-editor.vue
  src/components/helpers/slide-toc-button.vue
  src/components/image-editor.vue
  src/components/metadata-editor.vue
  src/components/preview.vue
  src/components/slide-editor.vue
  src/components/slideshow-editor.vue
  src/components/video-editor.vue
  src/definitions.ts
Labels: PR: Active, PR: Frontend

#566 Improve slideshow editor
  src/components/editor.vue
  src/components/metadata-editor.vue
  src/components/slideshow-editor.vue
  src/lang/lang.csv
Labels: PR: Frontend

#580 Fix lang change for Canada.ca template
  index-ca-en.html
  index-ca-fr.html
Labels: PR: Frontend

#585 Reroute to Dashboard when using Canada.ca template
  src/components/landing.vue
Labels: PR: Frontend

#571 Reintroduce garbage collection
  server/index.js
Labels: PR: Active
