Repository ramp4-pcar4/storylines-editor, pull requests merged in 2025-06, with the labels that each got.

#605 Unique path for metadataNew
  index-ca-en.html
  index-ca-fr.html
  src/router/index.ts
Labels: PR: Frontend

#575 Implement robust, lightweight state tracking
  package-lock.json
  package.json
  public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_en.json
  public/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000_fr.json
  src/components/chart-editor.vue
  src/components/dynamic-editor.vue
  src/components/editor.vue
  src/components/image-editor.vue
  src/components/map-editor.vue
  src/components/metadata-editor.vue
  src/components/slide-editor.vue
  src/components/slide-toc.vue
  src/components/text-editor.vue
  src/components/video-editor.vue
  src/lang/lang.csv
  src/stores/stateStore.ts
Labels: PR: Active, PR: Frontend

#637 update Storylines verson; allow string template rendering
  package-lock.json
  package.json
  src/lang/lang.csv
  vite.config.mts
Labels: PR: Frontend

#602 Standardize UI element CSS
  src/components/chart-editor.vue
  src/components/dynamic-editor.vue
  src/components/editor.vue
  src/components/helpers/action-modal.vue
  src/components/helpers/chart-preview.vue
  src/components/helpers/colour-picker-input.vue
  src/components/helpers/confirmation-modal.vue
  src/components/helpers/image-preview.vue
  src/components/helpers/metadata-content.vue
  src/components/helpers/multi-option-modal.vue
  src/components/helpers/time-slider-editor.vue
  src/components/home.vue
  src/components/image-editor.vue
  src/components/map-editor.vue
  src/components/metadata-editor.vue
  src/components/preview.vue
  src/components/slide-editor.vue
  src/components/slide-toc.vue
  src/components/slideshow-editor.vue
  src/components/text-editor.vue
  src/components/video-editor.vue
  src/lang/lang.csv
  src/main.ts
  src/standard-components.css
  src/style.css
Labels: PR: Frontend

#635 Ensure only one preview gets BroadcastChannel
  src/components/preview.vue
Labels: PR: Frontend

#614 Fixed so that ToC orientation and return to top changes for both langs
  src/components/helpers/metadata-content.vue
  src/components/metadata-editor.vue
  src/definitions.ts
  src/lang/lang.csv
Labels: PR: Frontend

#639 Fixed text editor overlap
  src/components/text-editor.vue
Labels: PR: Frontend

#640 Added hour and minute to last modified timestamp
  src/components/home.vue
Labels: PR: Frontend

#651 Fix non-highcharts WAVE errors
  src/components/helpers/custom-editor.vue
  src/components/slide-toc.vue
  src/components/text-editor.vue
  src/lang/lang.csv
Labels: PR: Frontend

#629 Create metadata modal component, Organize components folder
  src/components/editor.vue
  src/components/help/help-panel.vue
  src/components/help/help-section.vue
  src/components/helpers/metadata-content.vue
  src/components/metadata/metadata-content.vue
  src/components/metadata/metadata-editor.vue
  src/components/metadata/metadata-modal.vue
  src/components/panel-editors/chart-editor.vue
  src/components/panel-editors/custom-editor.vue
  src/components/panel-editors/dynamic-editor.vue
  src/components/panel-editors/image-editor.vue
  src/components/panel-editors/map-editor.vue
  src/components/panel-editors/slideshow-editor.vue
  src/components/panel-editors/text-editor.vue
  src/components/panel-editors/video-editor.vue
  src/components/preview.vue
  src/components/slide-editor.vue
  src/components/slide-toc/slide-toc-button.vue
  src/components/slide-toc/slide-toc.vue
  src/components/slide-toc/toc-options.vue
  src/components/support/action-modal.vue
  src/components/support/chart-preview.vue
  src/components/support/colour-picker-input.vue
  src/components/support/confirmation-modal.vue
  src/components/support/dropdown-menu.vue
  src/components/support/image-preview.vue
  src/components/support/loading-page.vue
  src/components/support/multi-option-modal.vue
  src/components/support/time-slider-editor.vue
  src/components/support/video-preview.vue
  src/components/support/wet-component-templates.json
  src/components/support/wet-dashboard-item.vue
  src/router/index.ts
Labels: PR: Active
