Repository ramp4-pcar4/storylines-editor, pull requests merged in 2025-08, with the labels that each got.

#712 Made MD editor French compliant
  src/components/panel-editors/text-editor.vue
  src/lang/lang.csv
  src/main.ts
  src/plugins/markdown-editor/index.ts
  src/shims-vue.d.ts
Labels: PR: Frontend

#718 Be able to reupload the same picture after deleting it
  src/components/metadata/metadata-editor.vue
Labels: PR: Frontend

#710 Fix edit button for charts
  src/components/panel-editors/chart-editor.vue
Labels: PR: Frontend

#694 Prevent console spamming when entering new uuid
  src/components/metadata/metadata-editor.vue
Labels: PR: Frontend

#689 Added footer padding in preview, updated storylines version
  src/components/preview.vue
Labels: PR: Frontend

#659 feat: Refresh dynamic editor table & functionality
  src/components/panel-editors/dynamic-editor.vue
  src/components/panel-editors/slideshow-editor.vue
  src/lang/lang.csv
Labels: Enhancement, Dynamic, PR: Frontend

#692 Add support for captions and transcripts
  src/components/home.vue
  src/components/panel-editors/video-editor.vue
  src/lang/lang.csv
Labels: PR: Frontend

#690 Prevent saving invalid config in advanced editor
  src/components/panel-editors/custom-editor.vue
Labels: PR: Frontend

#741 Updated version for pinia, HACK, and storylines
  package-lock.json
  package.json
  src/lang/lang.csv
Labels: PR: Build

#657 feat: Implement undo/redo, clickable mini-icons
  src/components/editor.vue
  src/components/metadata/metadata-editor.vue
  src/components/panel-editors/dynamic-editor.vue
  src/components/panel-editors/image-editor.vue
  src/components/slide-editor.vue
  src/components/slide-toc/slide-toc-button.vue
  src/components/slide-toc/slide-toc.vue
  src/definitions.ts
  src/lang/lang.csv
  src/stores/productStore.ts
  src/stores/stateStore.ts
Labels: Enhancement, Refactor, PR: Active, PR: Frontend
